apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-db
  template:
    metadata:
      labels:
        app: oracle-db
    spec:
      containers:
      - name: oracle-db
        image: gvenzl/oracle-free
        ports:
        - containerPort: 1521
        env:
        - name: ORACLE_PASSWORD
          value: "admin"
        - name: APP_USER
          value: "admin"
        - name: APP_USER_PASSWORD
          value: "admin"
        - name: ORACLE_DATABASE
          value: "reciclagem"
        volumeMounts:
        - name: oracle-storage
          mountPath: /opt/oracle/oradata
      volumes:
      - name: oracle-storage
        persistentVolumeClaim:
          claimName: oracle-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-service
spec:
  type: ClusterIP
  ports:
    - port: 1521
  selector:
    app: oracle-db
