apiVersion: apps/v1
kind: Deployment
metadata:
  name: csharp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: csharp-app
  template:
    metadata:
      labels:
        app: csharp-app
    spec:
      containers:
      - name: csharp-app
        image: lilartdev/api_reciclagem_prod:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__DefaultConnection
          value: ${{ secrets.CONNECTION_STRING_PRODUCTION }}
---
apiVersion: v1
kind: Service
metadata:
  name: csharp-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: csharp-app
