apiVersion: apps/v1
kind: Deployment
metadata:
  name: csharp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csharp-app
  template:
    metadata:
      labels:
        app: csharp-app
    spec:
      containers:
      - name: csharp-app
        image: lilartdev/api_reciclagem_staging:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Staging"
        - name: ConnectionStrings__DefaultConnection
          value: "User Id=admin;Password=admin;Data Source=oracle-service:1521/reciclagem;"
---
apiVersion: v1
kind: Service
metadata:
  name: csharp-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: csharp-app
