name: CI-CD Pipeline for Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -c Release -o out

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Build Docker image for Production
      run: docker build -t lilartdev/reciclagem_api_prod:${{ github.sha }} .

    - name: Tag Docker image with latest
      run: docker tag lilartdev/reciclagem_api_prod:${{ github.sha }} lilartdev/reciclagem_api_prod:latest

    - name: Push Docker image to Docker Hub (Production SHA tag)
      run: docker push lilartdev/reciclagem_api_prod:${{ github.sha }}

    - name: Push Docker image to Docker Hub (latest tag)
      run: docker push lilartdev/reciclagem_api_prod:latest
