name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -c Release -o out

    - name: Build Docker image
      run: docker build -tlilartdev/api_reciclagem_staging:${{ github.sha }} .

    - name: Push Docker image to Docker Hub
      run: docker push lilartdev/api_reciclagem_staging:${{ github.sha }}
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy_staging:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Setup kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.20.0'

    - name: Deploy Oracle DB for Staging
      run: kubectl apply -f k8s/k8s-oracle-deployment-staging.yaml

    - name: Deploy Staging App
      run: |
        kubectl set image deployment/csharp-app csharp-app=suaimagem/csharp-app:${{ github.sha }}
        kubectl apply -f k8s/k8s-deployment-staging.yaml
